### ISSUE TITLE
Intro to WebVR using A-Frame

### ISSUE THREAD

**Issue by stowball** [newwwie/newcastlejs-meetup#1]
## About
How to use [A-Frame](https://aframe.io/) to build interactive VR experiences that work in the browser (and enhancing with Vue,js)

## Duration
15–30 mins

## Target Audience
Beginners/Intermediate

## Hardware
I'll bring a VR headset or 2

## Date
Whenever

**Comment by neozenith** [comment]
Sounds awesome! Just a matter of confirming if you want to do June or another month?

**Comment by stowball** [comment]
I can't do July actually (I'll need to be on call for the final game of State Of Origin), so happy to do June or any other month

**Comment by neozenith** [comment]
Ok we'll lock in June. 👍

**Comment by neozenith** [comment]
Oh wait... Might bump this to August if that is all the same. I forgot @cathylill claimed June for her talk which is a trial run for a conference...

**Comment by stowball** [comment]
Sounds good 👍
