### ISSUE TITLE
CSS Architecture for Modern JavaScript Applications

### ISSUE THREAD

**Issue by MadeByMike** [newwwie/newcastlejs-meetup#10]
## Title

CSS Architecture for Modern JavaScript Applications

## Description

How we build and maintain style systems has changed in the last few year. Tasks that once required specific knowledge and careful management are now trusted to build tools and frameworks with better precision than was possible using conventions like BEM. Are all these conventions dead? If so, what has replaced them? Or, are some lessons from the past still relevant?

## Presenter Bio

Mike is an independent web developer from Australia who has worked on some of Australia’s largest websites as well as some of the smallest community sites. He loves learning new things and finding techniques that challenge what we think is best practice. And when he’s not exploring the digital landscape, he likes to explore the world. Currently trying to find a way to do both those things at the same time.

## Promo Photos

https://www.madebymike.com.au/img/mug/mike.jpg

----

## Duration

30min

## Target Audience

Intermediate & Advanced

## Hardware
USBC to HDMI ? - (Mac Book Pro) I'll try and bring an adapter but good to have backup :)

## Date

Next Meetup i.e. Nov?

**Comment by domsammut** [comment]
Hey Mike,

So sorry for the delayed response. I've been overseas for the last month. Are you still open to presenting in November? Feel free to reach out to me on the [newwwie](https://newwwie.com/#invite) slack channel (I couldn't seem to find you on there).

Cheers
Dom

**Comment by MadeByMike** [comment]
@domsammut I'll jump on the slack channel. Obviously we've missed it for November but perhaps another event.

**Comment by MadeByMike** [comment]
Sorry, my github notifications are a fire-hose and I don't see everything

**Comment by domsammut** [comment]
@MadeByMike no problem! I'll touch base with you there :)
