### ISSUE TITLE
Embedding Javascript from Vanilla to Embedded Components

### ISSUE THREAD

**Issue by bjcull** [newwwie/newcastlejs-meetup#2]
## Title
Embedding Javascript from Vanilla to Embedded Components

## About
I have an embedded widget that I offer to third parties to use. This is how I built the original using plain ol' javascript, and me tinkering with the latest embedded widget tech from Angular and possibly react if I get there.

## Duration
1 hour

## Target Audience
Intermediate

## Hardware
HDMI, some sort of brain pooper-scooper to clean up all of the blown minds.

## Date
June 13 is fine, months after that are probably OK too

**Comment by neozenith** [comment]
Sounds great and thanks for proposing the talk! We are looking at having #1 for June so how does July suit you?

**Comment by neozenith** [comment]
Updated speaker schedule. This is scheduled for October after verbal confirmation tonight at the meetup 👍 🙌 💯 :shipit: 🚀
