### ISSUE TITLE
Talk

### ISSUE THREAD

**Issue by seanstanden** [newwwie/newcastlejs-meetup#5]
## Title
TBD

## About
nrgx

## Duration
20-30 min

## Target Audience
Beginners

## Date
Nov

**Comment by neozenith** [comment]
@seanstanden,

Thanks for the talk submission! For us to go ahead and confirm your slot for November we'll need the following for the Meetup event:

- A talk title
- 2-3 sentences describing your talk.
- 2 sentences describing yourself
- A promo picture of yourself
- You company logo

**Comment by seanstanden** [comment]
Thanks @neozenith I'm gonna need to pull out at this point, but will submit again soon. Cheers.

**Comment by neozenith** [comment]
@seanstanden Thanks for the offer. It is much appreciated.
