### ISSUE TITLE
Javascript and IoT

### ISSUE THREAD

**Issue by almcgoo** [newwwie/newcastlejs-meetup#8]
----

## Title
Javascript and IoT

## Description
Yes, you can use Javascript on a "thing" (IoT device) and make it useful (maybe).

Live demonstration on how to get a thing (tiny WiFi-enabled board that runs JavaScript code) connected to the world and attempt to do something that will change the world (at least turn a LED on/off or something).    

## Presenter Bio

I started working in Industrial Electronics in 1982 with 8 bit microprocessors, spent 10 years looking after the largest Mainframes in the country, followed by building and running a SaaS offering for the past 15 years.  Yep, I have grey hair...

Today, it is a 360 degree moment, working with microprocessors connected to some of the largest compute and SaaS offerings on the planet.  Who would have thunk it could be done with a total cost of a few dollars.

## Promo Photos

I'm shy...
----

## Duration

Will need the 40 - 50.  Don't worry it will be funny.

## Target Audience

Everyone

## Hardware

Should be OK.

## Date

Happy to do March with a caveat (waiting on some hardware to arrive next week)

## Misc

 It could be interesting as I haven't used this particular hardware before.
 
----

**Comment by neozenith** [comment]
That would be amazing! We desperately need a speaker for March. I’ll coordinate with you on Newwwie Slack.

**Comment by domsammut** [comment]
Awesome talk delivered! Thanks so much for stepping up Alan!
