### ISSUE TITLE
WebAssembly with Rust

### ISSUE THREAD

**Issue by neozenith** [newwwie/newcastlejs-meetup#9]
## Title
WebAssembly with Rust

## Description

https://pragprog.com/book/khrust/programming-webassembly-with-rust
So I bought this book on a whim because I have been wanting to learn WebAssembly and Rust as two different topics so I'm committing to doing a talk to make sure I finish the book.

I'll aim to demonstrate the exercises and key learnings or stumbling blocks. Some of it will be browser based and also some Raspberry Pi demonstration.

## Presenter Bio

Data Scientist, Software Engineer and polyglot programmer. I love studying programming languages as much as I love updating my Vim plugins and tooling.
 
Having worked on:
- Python/Ruby Data Engineering
- TemporalSpatial C++/Docker Applications 
- Heroku NodeJS OAuth API Integrations
- RaspberryPi and Arduino
- iOS ObjectiveC apps
- Java Applets

I'm looking forward to adding Rust and WebAssembly to my repertoire.

## Promo Photos
Use github photo

----

## Duration
30 minutes

## Target Audience
Beginners

## Hardware
HDMI is fine

## Date
July is free so I'll aim for that.

## Misc

 
----

**Comment by jnowland** [comment]
We still have availability in July - are you still keen @neozenith ?

**Comment by neozenith** [comment]
I’ve gone cold on this topic.

 I could do a talk on interactive data visualisation with Jupyter Notebooks and Altair instead.
